service:
  name: scraping-lambda-backoffice

plugins:
  - serverless-webpack
  - serverless-plugin-existing-s3
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x

functions:
  gm_location:
    handler: handler.gm_location
    events:
      - http:
          method: get
          path: gm_location